pitstop/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('listcat/', views.CategoryListView.as_view(), name='listcat'),
    path('list/', views.CategoryIndListView.as_view(), name='list'),
    path('detailcat/<int:pk>', views.CategoryDetailView.as_view(), name='detailcat'),
    path('search/', views.search_posts, name='search'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings

class Category(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.CharField(max_length=255)
    def __str__(self):
        return f'"{self.nome}"'

class Post(models.Model):
    post_url = models.URLField(max_length=200, null=True)
    titulo = models.CharField(max_length=255)
    data_publicacao = models.DateTimeField(auto_now_add = True)
    conteudo = models.CharField(max_length=5000)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.titulo} ({self.data_publicacao})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date_comment = models.DateTimeField(auto_now_add = True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'titulo',
            'post_url',
            'conteudo',
        ]
        labels = {
            'titulo': 'Título',
            'post_url': 'URL da imagem do Post',
            'conteudo': 'Conteúdo (HTML):',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Viajante:',
            'text': 'Comentário:',
        }

posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Comment, Post, Category
from .forms import PostForm, CommentForm
from django.views import generic

# Create your views here.
from django.http import HttpResponse
from .temp_data import post_data

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/listcat.html'

class CategoryIndListView(generic.ListView):
    model = Category
    template_name = 'posts/list.html'

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'posts/detailcat.html'

class PostCreateView(generic.CreateView):
    model = Post
    fields = ['titulo','post_url','conteudo','category']
    template_name = 'posts/create.html'

    def get_success_url(self):
        return reverse('posts:detail', kwargs={
            'pk': self.object.pk,
        })

class PostUpdateView(generic.UpdateView):
    model = Post
    fields = ['titulo','post_url','conteudo','category']
    template_name = 'posts/update.html'

    def get_success_url(self):
        return reverse('posts:detail', kwargs={
            'pk': self.object.pk,
        })
class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    def get_success_url(self):
        return reverse('posts:index')

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(name__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'posts/search.html', context)

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Post {{ post.titulo }} ({{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }})</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post de Receita/Restaurante</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o post "{{ post.titulo }} ({{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.titulo }} ({{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Post {{ post.titulo }} ({{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }})</h2>

<section class="dados-de-post">
    <img src="{{ post.post_url }}" alt="Imagem de {{ post.titulo}}">
    <ul>
        <li>Título: {{ post.titulo }}</li>
        <li>Conteúdo: {{ post.conteudo|safe|escape }}</li>
        <li>Data de criação: {{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }} </li>
        <li><strong>Categoria: {{ post.category.nome }} </strong></li>
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>
</section>
<section>
    <header>
        <h3>Comentários dos nossos viajantes</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>— {{ comment.author }} em {{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para este post.</p>
        {% endif %}
    </ul>
    
    <hr>

    <a href="{% url 'posts:comment' post.pk %}"><button>Faça o seu comentário</button></a>
</section>


{% endblock content %}

posts/templates/posts/detailcat.html
{% extends 'base.html' %}

{% block title %}
{{ category.nome }}
{% endblock title %}

{% block content %}
<h2>Detalhes da Categoria {{ category.titulo }} </h2>

<section class="dados-de-post">
    <ul>
        <li>Nome: {{ category.nome }}</li>
        <li>Descrição: {{ category.descricao }}</li>
        <li>Posts:</li>
    </ul>
{% if category.post_set.all %}
  {% for post in category.post_set.all %}
    <article class="post">
      <div><a href="{% url 'posts:detail' post.id %}"><img src="{{ post.post_url }}"
              alt="Imagem do post {{ post.titulo}}"></a></div>
      <div><p><a href="{% url 'posts:detail' post.id %}">{{ post.titulo }} ({{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }})</a></p></div>
    </article>
  {% endfor %}
{% else %}
   <p>Ainda não existe nenhum post para esta categoria.<br></p>
{% endif %}
</section>


{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'posts:search' %}">Buscar Posts</a></p>
    <p>Não encontrou o post? <a href="{% url 'posts:create' %}">Adicionar Novo Post</a></p>
</section>
{% if post_list %}
<section class="lista-de-posts">
    {% for post in post_list %}
    <article class="post">
        <div><a href="{% url 'posts:detail' post.id %}"><img src="{{ post.post_url }}"
                alt="Imagem do post {{ post.titulo}}"></a></div>
        <div><p><a href="{% url 'posts:detail' post.id %}">{{ post.titulo }} ({{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }})</a></p></div>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post. Tente ser menos específico no campo de busca, como o uso de palavras-chave</p>
{% endif %}

{% endblock content %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% block content %}
<h2>Todas as Categorias</h2>
{% if category_list %}
<section class="lista-de-posts">
    {% for category in category_list %}
    <article class="post">
        <div><p><h3><a href="{% url 'posts:detailcat' category.id %}">"{{ category.nome }}"</a></h3></p></div>
        <div><p><a href="{% url 'posts:detailcat' category.id %}">"{{ category.descricao }}"</a></p></div>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma categoria.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/listcat.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts e suas categorias</h2>
<section>
    <p>Não encontrou o post? <a href="{% url 'posts:create' %}">Adicionar Novo Post</a></p>
</section>
{% if category_list %}
<section class="lista-de-posts">
    {% for category in category_list %}
    <article class="post">
        <div><p><h3>"{{ category.nome }}"</h3></p></div>
        <div><p>"{{ category.descricao }}"</p></div>
    </article>
    {% if category.post_set.all %}
          {% for post in category.post_set.all %}
          <article class="post">
            <div><a href="{% url 'posts:detail' post.id %}"><img src="{{ post.post_url }}"
                    alt="Imagem do post {{ post.titulo}}"></a></div>
            <div><p><a href="{% url 'posts:detail' post.id %}">{{ post.titulo }} ({{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }})</a></p></div>
          </article>
         {% endfor %}
    {% else %}
         <p>Ainda não existe nenhum post para esta categoria.<br></p>
    {% endif %}



    
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post. Tente ser menos específico no campo de busca, como o uso de palavras-chave<br></p>
{% endif %}

{% endblock content %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Posts por Título</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-posts">
    {% for post in post_list %}
    <article class="post">
        <div><img src="{{ post.post_url }}" alt="Imagem do post {{ post.titulo}}"></div>
        <div><p>{{ post.titulo }} ({{ post.data_publicacao|date:"SHORT_DATE_FORMAT" }})</p></div>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca. Tente ser menos específico, como o uso de palavras-chave</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Post {{ post.titulo }} ({{ post.data_publicacao|date:"SHORT_DATE_FORMAT"}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | PitStop
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.png' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Posts</a></li> 
                <li><a href="{% url 'posts:listcat' %}">Posts por Categorias</a></li>
                <li><a href="{% url 'posts:list' %}">Lista de Categorias</a></li> 
                <li><a href="{% url 'about' %}">Sobre o PitStop</a></li>
            </ul>
        </nav>
    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021 - Rayan Luz Ralile - NUSP 12412502</small>
        </p>
    </footer>
</body>

</html>

templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<section class="lista-de-posts">
    <article class="single_index">
        <p>Este site foi desenvolvido para fins acadêmicos, de forma a cumprir atividade requisitada da disciplina PMR3304 Sistemas de Informação.</p>
        <p>Aluno: Rayan Luz Ralile<br>NUSP: 12412502</p>
    </article>
</section>
{% endblock content %}

templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1>PitStop da estrada</h1>
<p>A Página gastronômica para os viajantes sobre rodas!</p>
<br>
<br>
<section class="lista-de-posts">
    <article class="single_index"><p>O objetivo desta página é oferecer aos visitantes a oportunidade de conhecer 
        pratos típicos de quem vive na estrada e ótimos restaurantes de estrada. Aqui você poderá também 
        contribuir com a comunidade, inserindo novos pratos ou estaurantes e ainda comentando, para dar maior 
        credibilidade a postagem. Seja muito bem-vindo</p>
        <p>Clique em <a href="{% url 'posts:index' %}"><strong>Posts</strong></a> para visualizar todas os pratos e restaurantes para poder curtir a culinária da estrada!</p>
        <div class = "truck">
            <a href="{% url 'posts:index' %}"> <img src="https://i.imgur.com/Hmk7d5M.jpeg"> </a>
                <a href="{% url 'posts:index' %}"> <img src="https://i.imgur.com/OSOAcfZ.jpeg"> </a>
                <a href="{% url 'posts:index' %}"> <img src="https://i.imgur.com/s9M5wo0.jpeg"> </a>
    </article>
</section>
{% endblock content %}